- codeOfConduct.mdown
To get the ball rolling...
Please have a read over it, pretty sure there are improvements to be made (see the management team comment).
#50 
(And yes, so far it is essentially a find and replace on 'conference' to 'meet-up').
> code of conduct

- _layouts/default.html
> Moved bootstrap to head

- .travis.yml
- CONTRIBUTING.md
- Gruntfile.js
- LICENSE.md
- README.md
> Adds license and Travis build

- Gruntfile.js
> Make sure UnCSS doesn't remove classes used by JS

- Gruntfile.js
Fixes header spacing issues by ignoring JS-added CSS rules in uncss.
> Fix event header spacing

- .travis.yml
This should notify us of build status in gitter
> gitter integration

- Gruntfile.js
> Fixed issue with uncss removing member photo css

- Gruntfile.js
> Fixed menu button on mobile

- _config.yml
> Removed Gruntfil from built site

- css/style.less
- js/script.js
- Reduced the amount of spacing below the header.
- Fixed overflow of event info (date/time/etc.) on post heading.
> Cleaned up some spacing/overflow issues

- index.html
See #65 
Mobile users will now see the Google map between upcoming events and past events.
> Show map to :iphone: users

- Gruntfile.js
More css classes used in JS.
(Need to look into having it check JS files somehow)
> Added more to uncss

- Gruntfile.js
I did this on summer of hacks https://github.com/jsoxford/summerofhacks.github.io/commit/289172a246560952dd43ca98f2ef23c273ba586e
It's kind of cute to have jsoxbot building our sites
[![image](https://cloud.githubusercontent.com/assets/51385/7432070/9c8248f0-f01c-11e4-902e-33a178d9cfd8.png)](https://github.com/jsoxford/summerofhacks.github.io/commits/gh-pages)
> Deploy as JSOxbot

- index.html
> Adding Summer of Hacks sticky post

- _posts/2015-05-02-jsoxford-for-newbies.md
In response to #108, a short blog post on what it's like to be a beginner.
> Added JSOxford for Newbies post

- .travis.yml
Not 100% sure though so wouldn't mind someone with travis experience (@spikeheap) to take a look first.
> I *think* this should fix the travis deploy.

- css/style.scss
Some tweaks to the styles, to improve things such as:
- visual hierarchy
- consistency
- font size
Also fixed some issues caused by the breakpoints around the header image, and the presentation of the members list on mobile.
Desktop:
Mobile:
> I'm in your CSS improving aesthetics.

- _layouts/post.html
- css/style.scss
Added some spacing next to the author name and made sure that markdown is parsed on individual post pages.
> Fix some stuff

- js/script.js
The JS was throwing an error due to a missing function. Re-added func.
> Added missing function

- welcome.html
I've tweaked the welcome page slightly - uses the font from the logo, and replaces the `ul` with a `table`
> Welcome tweaks

- _includes/sidebar.html
- _layouts/base.html
- css/style.scss
I'd like @omgmog to take a look to make sure he's happy with this.
If this is OK then the icons will need to be changed if #137 is accepted.
> Cleaned up social links and added youtube

- css/style.scss
> Clear float in sidebar

- js/script.js
Yeah, fixed #149. Should hopefully sort the weird timezone issue too until i can properly look at it.
> Fixed #149 - Update date/time of updated events

- welcome.html
After selecting the initial number of rows, press the `ins` key to add another.
> Add the ability to add more rows

- .travis.yml
See: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
/cc @spikeheap
> Upgrade travis to use containers

- Gruntfile.js
@spikeheap This looks to fix the issues we were seeing yesterday. This needs #158 to be reverted though.
> Fixed imagemin Grunt task

- welcome.html
Add the title of the meetup to the welcome page. More room for emojis :wink:
> Added meetup title to welcome page

- welcome.html
Try to auto populate the speaker list from the meetup event description. 
Any text in bold will be assumed to be a talk title. It is possible to modify this after its populated.
If no speakers are found it will prompt for how many and allow manual entry.
> If there is a meetup today, fetch the speaker list

- index.html
That, like, totally happened
cc/ #101
> Remove Summer of Hacks banner

- welcome.html
Makes sure the welcome page pulls in todays event
> Updated signed URL to include event time

- _includes/sidebar.html
- _layouts/base.html
Changed the map and link to point to the Story Museum ready for the next meetup.
If we are going to be alternating between meetup and social venues it might be best to change things to include that somehow.
> Changed location to The Story Museum :book:

- _includes/sidebar.html
@benfoxall mind taking a look?
> Changed link to issues

- index.html
Looks like I missed this previously.
> Change location of map on mobile

- CONTRIBUTING.md
This could even be ported to develop I guess...
> Update CONTRIBUTING.md on next branch

- .jscsrc
- CONTRIBUTING.md
- Gruntfile.js
- js/script.js
- package.json
Prevent me from messing up spaces/tabs etc.
@spikeheap this should make you happy. 
Are we happy with the [AirBNB](https://github.com/airbnb/javascript) rules for now?
> Enfore JS style using jscs

- package.json
@benfoxall This should fix the broken Travis build but can't say for sure until we try it.
> Bump module versions
